repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: pretty-format-json
        args: ["--autofix"]
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 24.12.0
    hooks:
      - id: black
        args: ["--target-version", "py311"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.8
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.2
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-pyyaml]
        args: ["--ignore-missing-imports"]
