#!/usr/bin/env bash
set -euo pipefail

# Antigravity Bootstrap Script
# Handles PAT configuration and existing bootstrap logic

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
LOG_FILE="${PROJECT_ROOT}/artifacts/logs/bootstrap_antigravity.log"

# Ensure artifacts directories exist
mkdir -p "${PROJECT_ROOT}/artifacts/logs"

# Logging function
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

log "=== Starting Antigravity Bootstrap ==="

# Check if already bootstrapped
MARKER_FILE="${PROJECT_ROOT}/artifacts/bootstrap_done.md"
if [ -f "$MARKER_FILE" ]; then
    log "Bootstrap already completed. Marker file exists: $MARKER_FILE"
    log "Skipping bootstrap process."
    exit 0
fi

# Step 1: Configure PAT from GCP Secret Manager
log "Step 1: Configuring GitHub PAT from GCP Secret Manager..."
if [ -x "${SCRIPT_DIR}/get_pat_from_gcp.sh" ]; then
    "${SCRIPT_DIR}/get_pat_from_gcp.sh"
    if [ $? -eq 0 ]; then
        log "✓ PAT configuration successful"
    else
        log "✗ PAT configuration failed"
        exit 1
    fi
else
    log "✗ PAT script not found or not executable: ${SCRIPT_DIR}/get_pat_from_gcp.sh"
    exit 1
fi

# Step 2: Run existing bootstrap logic
log "Step 2: Running existing bootstrap logic..."

# Try to find and run existing bootstrap scripts
BOOTSTRAP_FOUND=false

# Check for tools/bootstrap_gh.sh
if [ -x "${PROJECT_ROOT}/tools/bootstrap_gh.sh" ]; then
    log "Found existing bootstrap script: tools/bootstrap_gh.sh"
    "${PROJECT_ROOT}/tools/bootstrap_gh.sh" verify
    if [ $? -eq 0 ]; then
        BOOTSTRAP_FOUND=true
        log "✓ Existing bootstrap verification successful"
    else
        log "✗ Existing bootstrap verification failed"
        exit 1
    fi
fi

# Check for CLI.POSTBOOT script
if [ -x "${PROJECT_ROOT}/CLI.POSTBOOT.250.sh" ]; then
    log "Found CLI.POSTBOOT script: CLI.POSTBOOT.250.sh"
    "${PROJECT_ROOT}/CLI.POSTBOOT.250.sh"
    if [ $? -eq 0 ]; then
        BOOTSTRAP_FOUND=true
        log "✓ CLI.POSTBOOT script executed successfully"
    else
        log "✗ CLI.POSTBOOT script failed"
        exit 1
    fi
fi

# If no existing bootstrap found, just log it
if [ "$BOOTSTRAP_FOUND" = false ]; then
    log "No existing bootstrap scripts found. Proceeding with PAT-only bootstrap."
fi

# Step 3: Create marker file
log "Step 3: Creating bootstrap completion marker..."
mkdir -p "${PROJECT_ROOT}/artifacts"

cat > "$MARKER_FILE" << EOF
# Antigravity Bootstrap Completed

Bootstrap completed successfully on: $(date -u +%Y-%m-%dT%H:%M:%SZ)

## Completed Tasks:
- ✅ GitHub PAT configured from GCP Secret Manager
- ✅ Existing bootstrap logic executed (if present)
- ✅ Antigravity self-bootstrap infrastructure ready

## Notes:
- PAT stored in ~/.git-credentials for HTTPS authentication
- Git credential helper configured to use stored credentials
- Marker file prevents re-running bootstrap on subsequent runs

Generated by: scripts/bootstrap_antigravity.sh
EOF

log "✓ Bootstrap marker created: $MARKER_FILE"

log "=== Antigravity Bootstrap Completed Successfully ==="

# Display completion message
cat << EOF

🎉 Antigravity Bootstrap Complete!

GitHub PAT has been configured and stored in ~/.git-credentials
Existing bootstrap logic has been executed (if present)
Bootstrap marker created at: artifacts/bootstrap_done.md

Antigravity is now ready for operation.

EOF
