name: Agent Preflight Checks

on:
  pull_request:
    branches: [ main ]
    paths:
      - '.agents/**'
      - 'AGENT_RUNBOOK.md'
      - '.gitignore'

jobs:
  agent-consistency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Gemini sandbox guards
        run: |
          echo "🔍 Checking Gemini sandbox variables in launcher..."
          grep -q "GEMINI_SANDBOX GEMINI_CLI_SANDBOX GEMINI_TOOLS_SANDBOX GEMINI_TOOL_SANDBOX GEMINI_EXTENSIONS_SANDBOX" .agents/gemini/start.sh || exit 1
          echo "✅ All 5 sandbox variables present in start.sh"

          echo "🔍 Checking Gemini sandbox variables in runbook..."
          grep -q "GEMINI_SANDBOX GEMINI_CLI_SANDBOX GEMINI_TOOLS_SANDBOX GEMINI_TOOL_SANDBOX GEMINI_EXTENSIONS_SANDBOX" .agents/gemini/runbook.md || exit 1
          echo "✅ All 5 sandbox variables present in runbook"

      - name: Verify Claude flag consistency
        run: |
          echo "🔍 Checking Claude uses --allowed-tools in launcher..."
          grep -q "\\-\\-allowed-tools" .agents/claude/start.sh || exit 1
          echo "✅ Claude launcher uses --allowed-tools"

          echo "🔍 Checking Claude uses --allowed-tools in runbook..."
          grep -q "\\-\\-allowed-tools" .agents/claude/runbook.md || exit 1
          echo "✅ Claude runbook uses --allowed-tools"

          echo "🔍 Checking no incorrect --tools in Claude files..."
          ! grep -q "\\-\\-tools" .agents/claude/start.sh || exit 1
          ! grep -q "\\-\\-tools" .agents/claude/runbook.md || exit 1
          echo "✅ No incorrect --tools flags in Claude files"

      - name: Verify overview consistency
        run: |
          echo "🔍 Checking AGENT_RUNBOOK.md Claude section uses --allowed-tools..."
          grep -A 20 "### Claude Code Agent" AGENT_RUNBOOK.md | grep -q "\\-\\-allowed-tools" || exit 1
          echo "✅ Overview Claude section uses --allowed-tools"

          echo "🔍 Checking AGENT_RUNBOOK.md Gemini section has sandbox guards..."
          grep -A 20 "### Gemini CLI Agent" AGENT_RUNBOOK.md | grep -q "GEMINI_SANDBOX GEMINI_CLI_SANDBOX GEMINI_TOOLS_SANDBOX GEMINI_TOOL_SANDBOX GEMINI_EXTENSIONS_SANDBOX" || exit 1
          echo "✅ Overview Gemini section has sandbox guards"

      - name: Verify .agents directory not ignored
        run: |
          echo "🔍 Checking .agents/ not ignored in .gitignore..."
          ! grep -q "^\.agents/" .gitignore || exit 1
          echo "✅ .agents/ directory not ignored"

      - name: Check CLI availability (log only)
        run: |
          echo "🔍 Checking Gemini CLI availability..."
          gemini --version || echo "ℹ️  Gemini CLI not available on runner (expected)"

          echo "🔍 Checking Claude CLI availability..."
          claude --version || echo "ℹ️  Claude CLI not available on runner (expected)"

      - name: Guard against lockfile changes
        run: |
          echo "🔍 Checking for lockfile changes..."
          if git diff --name-only origin/main... | grep -E '(package-lock\.json|poetry\.lock|requirements\.txt)$'; then
            echo "❌ Lockfile changes detected - this breaks agent isolation"
            exit 1
          fi
          echo "✅ No lockfile changes detected"
