name: Agent E2E
on:
  push:
    branches: [main]
    paths: ['tests/**', 'scripts/**', 'agent_data/**']
  pull_request:
    paths: ['tests/**', 'scripts/**', 'agent_data/**']
  workflow_dispatch:
    inputs:
      e2e:
        description: 'Run E2E tests'
        required: false

jobs:
  agent-e2e:
    name: Agent E2E (CPG1.1, CPG1.2)
    runs-on: ubuntu-22.04
    if: github.event.label.name == 'e2e' || github.event.inputs.e2e == 'true'
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      QDRANT_API_KEY: ${{ secrets.QDRANT_CLUSTER1_KEY }}
      QDRANT_CLUSTER_ID: ${{ secrets.QDRANT_CLUSTER1_ID }}
      QDRANT_REGION: "asia-southeast1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install langroid==0.58.0 pytest
      - name: Smoke test
        run: |
          python scripts/gen_fixtures.py --no-mock
          pytest tests/test_fixture_pipeline.py -m fixture --disable-warnings
