name: Agent E2E

on:
  workflow_call:
  workflow_dispatch:

jobs:
  agent-e2e:
    name: Agent E2E (CPG1.1, CPG1.2)
    runs-on: ubuntu-22.04
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request'
      && contains(github.event.pull_request.labels.*.name, 'e2e'))
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GCP_WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      QDRANT_CLUSTER1_KEY: ${{ secrets.QDRANT_CLUSTER1_KEY }}
      QDRANT_CLUSTER1_ID: ${{ secrets.QDRANT_CLUSTER1_ID }}
    timeout-minutes: 25
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: pip
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        token_format: access_token
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: latest
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run E2E tests
      run: |
        echo "=== Agent E2E Test ==="
        echo "Running tests per CPG1.1 and CPG1.2 requirements"
        python -m pytest tests/test_agent_data_unit.py::test_agent_flow -v
        python -m pytest tests/test_foundation.py::test_foundation_critical_green -v
    - name: Save logs
      if: always()
      run: |
        mkdir -p test-logs
        echo "Test run completed at $(date)" > test-logs/e2e-summary.txt
        echo "Status: ${{ job.status }}" >> test-logs/e2e-summary.txt
    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: e2e-test-logs
        path: test-logs/
        retention-days: 7
