name: Artifact Audit (Monitor)

on:
  workflow_dispatch:
  schedule:
    - cron: '20 3 * * *'   # chạy mỗi ngày; giá trị không quan trọng với B2

permissions:
  contents: read

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Sanity echo (placeholder)
        run: |
          set -euo pipefail
          echo "Monitor running: $GITHUB_WORKFLOW @ $GITHUB_SHA on $GITHUB_REF"
