name: CI

on:
  push:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.11"

jobs:
  lint:
    name: Code Quality & Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e ".[dev]"

      - name: Run Black
        run: black --check agent_data tests

      - name: Run isort
        run: isort --check-only agent_data tests

      - name: Run flake8
        run: flake8 agent_data tests

      - name: Run mypy
        run: mypy agent_data

      - name: Verify Dependencies
        run: |
          python -c "import langroid; from importlib.metadata import version; print(f'Langroid version: {version(\"langroid\")}')" || echo "Langroid optional dependency not found"

  actionlint:
    name: GitHub Actions Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          fail_on_error: false
