name: Cloud Run Deploy (Manual)
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: Tag to deploy
        default: "latest"
      allow_unauthenticated:
        description: Make service public
        type: boolean
        default: false
      service:
        description: Cloud Run service name
        default: "agent-data-test"
concurrency:
  group: cloudrun-deploy-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
  id-token: write
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  AR_REPO: agent-data
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auth to GCP (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Deploy
        shell: bash
        run: |
          SERVICE="${{ inputs.service }}"
          TAG="${{ inputs.image_tag }}"
          IMAGE="${REGION}-docker.pkg.dev/${PROJECT_ID}/${AR_REPO}/${SERVICE}:${TAG}"
          if [[ "${{ inputs.allow_unauthenticated }}" == "true" ]]; then
            AUTH_FLAG="--allow-unauthenticated"
          else
            AUTH_FLAG="--no-allow-unauthenticated"
          fi
          gcloud run deploy "$SERVICE" \
            --image "$IMAGE" \
            --region "$REGION" \
            --platform managed \
            $AUTH_FLAG \
            --quiet

  deploy-canary:
    name: Deploy Canary (no-traffic)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
      AR_REPO: agent-data
      SERVICE: ${{ inputs.service || 'agent-data-test' }}
    steps:
      - uses: actions/checkout@v4

      - name: Auth to GCP (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Deploy canary revision with no traffic
        id: canary
        shell: bash
        run: |
          set -euo pipefail
          SERVICE="${{ inputs.service || 'agent-data-test' }}"
          TAGVAL="${{ inputs.image_tag || 'latest' }}"
          IMAGE="${REGION}-docker.pkg.dev/${PROJECT_ID}/${AR_REPO}/${SERVICE}:${TAGVAL}"
          REV_TAG="canary-${GITHUB_SHA::7}"
          echo "image=${IMAGE}" >> "$GITHUB_OUTPUT"
          echo "rev_tag=${REV_TAG}" >> "$GITHUB_OUTPUT"
          gcloud run deploy "$SERVICE" \
            --image "$IMAGE" \
            --region "$REGION" \
            --platform managed \
            --tag "$REV_TAG" \
            --no-traffic \
            --quiet

      - name: Resolve canary URL
        id: resolve
        shell: bash
        run: |
          set -euo pipefail
          SERVICE="${{ inputs.service || 'agent-data-test' }}"
          REV_TAG="${{ steps.canary.outputs.rev_tag }}"
          URL=$(gcloud run services describe "$SERVICE" --region "$REGION" --format "value(status.traffic[?(@.tag=='${REV_TAG}')].url)")
          if [[ -z "$URL" ]]; then
            echo "Failed to resolve canary URL for tag $REV_TAG" >&2
            exit 1
          fi
          echo "url=$URL" >> "$GITHUB_OUTPUT"
          echo "Canary URL: $URL"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install test deps (smoke)
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests

      - name: Run smoke tests against canary URL
        env:
          CANARY_URL: ${{ steps.resolve.outputs.url }}
        run: |
          pytest -q -m smoke
