name: Deploy Artifact Lifecycle Functions

on:
  push:
    branches: [ main ]
    paths:
      - 'functions/mark_stale_artifacts/**'
      - 'functions/report_stale_artifacts/**'
      - '.github/workflows/deploy-functions.yml'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auth to GCP (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Deploy mark-stale-artifacts
        run: |
          gcloud functions deploy mark-stale-artifacts \
            --gen2 --runtime python312 --region "$REGION" \
            --source functions/mark_stale_artifacts \
            --entry-point handle --trigger-http --no-allow-unauthenticated \
            --set-env-vars PROJECT_ID=$PROJECT_ID,REGION=$REGION,AR_REPO=agent-data-test,AR_PACKAGE=agent-data-test,TTL_DAYS=14,IMPORTANT_TAGS=latest,stable

      - name: Deploy report-stale-artifacts
        run: |
          gcloud functions deploy report-stale-artifacts \
            --gen2 --runtime python312 --region "$REGION" \
            --source functions/report_stale_artifacts \
            --entry-point handle --trigger-http --no-allow-unauthenticated \
            --set-env-vars PROJECT_ID=$PROJECT_ID,REGION=$REGION,AR_REPO=agent-data-test,AR_PACKAGE=agent-data-test,SLACK_SECRET_NAME=SLACK_WEBHOOK_URL

