name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (WIF)
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          create_credentials_file: true
          export_environment_variables: true

      - name: Export Firebase credentials JSON
        id: firebase-creds
        run: |
          python - <<'PY' >> "$GITHUB_OUTPUT"
          import os
          path = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
          with open(path, "r", encoding="utf-8") as fh:
              data = fh.read()
          print("json={}".format(data.replace("\n", "\\n")))
          PY

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: app-service-project/package-lock.json

      - name: Install dependencies
        run: npm ci --prefix app-service-project

      - name: Build frontend
        run: npm run build --prefix app-service-project

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ steps.firebase-creds.outputs.json }}
          projectId: github-chatgpt-ggcloud
          channelId: live
          entryPoint: app-service-project
