name: E2E Smoke Test

on:
  pull_request:

jobs:
  auth-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'
          cache-dependency-path: app-service-project/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: app-service-project

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
        working-directory: app-service-project

      - name: Run authentication smoke test
        run: npm run test:e2e
        working-directory: app-service-project
