name: Lint Only

on:
  workflow_call:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Run linters
      run: |
        echo "=== Linting Check ==="
        echo "Running linting per code quality standards"
        pre-commit run --all-files --show-diff-on-failure
    - name: Check imports
      run: |
        echo "=== Import Analysis ==="
        python -c "
        import sys
        import importlib.util

        # Check critical imports
        modules = ['langroid', 'qdrant_client', 'openai']
        for module in modules:
            try:
                spec = importlib.util.find_spec(module)
                if spec:
                    print(f'✅ {module}: available')
                else:
                    print(f'❌ {module}: not found')
                    sys.exit(1)
            except Exception as e:
                print(f'❌ {module}: error - {e}')
                sys.exit(1)
        print('All critical modules available')
        "
    - name: Validate project structure
      run: |
        echo "=== Project Structure Validation ==="

        # Check required files
        required_files=(
          'pyproject.toml'
          'requirements.txt'
          'requirements-dev.txt'
          'agent_data/__init__.py'
          'agent_data/server.py'
          'agent_data/cli.py'
        )

        for file in "${required_files[@]}"; do
          if [[ -f "$file" ]]; then
            echo "✅ $file: exists"
          else
            echo "❌ $file: missing"
            exit 1
          fi
        done

        # Check directory structure
        required_dirs=(
          'agent_data'
          'tests'
          'scripts'
          'terraform'
          'functions'
        )

        for dir in "${required_dirs[@]}"; do
          if [[ -d "$dir" ]]; then
            echo "✅ $dir/: exists"
          else
            echo "❌ $dir/: missing"
            exit 1
          fi
        done

        echo "Project structure validation complete"
    - name: Test import paths
      run: |
        echo "=== Import Path Testing ==="
        python -c "
        try:
            from agent_data import cli, server
            print('✅ Main modules import successfully')
        except ImportError as e:
            print(f'❌ Import error: {e}')
            exit(1)
        "
    - name: Lint summary
      if: always()
      run: |
        echo "=== Lint Summary ==="
        echo "Timestamp: $(date -Iseconds)"
        echo "Status: ${{ job.status }}"
        echo ""
        echo "This lint check ensures compliance with:"
        echo "- Code quality standards"
        echo "- Import resolution"
        echo "- Project structure integrity"
        echo "- Pre-commit hook requirements"
