name: Live E2E Tests

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  run-live-tests:
    runs-on: ubuntu-22.04
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GCP_WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
      # Optional overrides for discovery
      GCP_REGION: asia-southeast1
      GCP_RUN_SERVICE: agent-data-test

      # Enable live e2e tests (tests are skipped unless this is set)
      E2E_LIVE_ENABLE: "1"
      # Temporarily disable Firestore metadata assertion if IAM is not provisioned
      E2E_LIVE_REQUIRE_FIRESTORE: "0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.GCP_WIF_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}

      - name: Fetch live E2E secrets
        id: fetch-secrets
        uses: google-github-actions/get-secret-manager-secrets@v1
        with:
          secrets: |
            qdrant_api_key:projects/${{ env.GCP_PROJECT_ID }}/secrets/QDRANT_API_KEY
            qdrant_url:projects/${{ env.GCP_PROJECT_ID }}/secrets/QDRANT_URL
            openai_api_key:projects/${{ env.GCP_PROJECT_ID }}/secrets/OPENAI_API_KEY

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e . pytest pytest-cov httpx

      - name: Run live E2E tests
        run: |
          # Override repo addopts (unit-only + coverage threshold) for live E2E run
          pytest -m e2e -q -o addopts=""
        env:
          OPENAI_API_KEY: ${{ steps.fetch-secrets.outputs.openai_api_key }}
          QDRANT_API_KEY: ${{ steps.fetch-secrets.outputs.qdrant_api_key }}
          QDRANT_URL: ${{ steps.fetch-secrets.outputs.qdrant_url }}
