name: Pass Gate
on:
  pull_request:
  push:
    branches: [ main ]
permissions:
  contents: read
jobs:
  pass-gate:
    runs-on: ubuntu-latest
    steps:
      - name: Green skip — no Apply here
        run: |
          echo "::notice::Pass Gate is monitor-only; no GCP creds → green."
          exit 0
