name: Pass Gate
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  skip-when-no-creds:
    if: ${{ !(secrets.GCP_WIF_PROVIDER != '' || secrets.GCP_SA_KEY_JSON != ''') }}
    runs-on: ubuntu-latest
    steps:
      - name: No creds → green skip
        run: |
          echo "::notice::No GCP creds (GCP_WIF_PROVIDER/GCP_SA_KEY_JSON) -> skipping Pass Gate by policy."
          exit 0

  plan:
    if: ${{ secrets.GCP_WIF_PROVIDER != '' || secrets.GCP_SA_KEY_JSON != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.*"
      - name: Terraform init
        working-directory: terraform
        run: terraform init -input=false -no-color
      - name: Terraform plan
        working-directory: terraform
        env:
          TF_INPUT: "false"
        run: terraform plan -input=false -no-color
