name: Pass Gate
on:
  pull_request_target:
    types: [closed]
    branches: [main]
jobs:
  ensure-green:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check combined status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SHA=${{ github.event.pull_request.merge_commit_sha }}
          STATE=$(curl -s -H "Authorization: token $GH_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/commits/$SHA/status \
            | jq -r .state)
          if [[ "$STATE" != "success" ]]; then
            echo "::error::Merged while CI=$STATE – revert!"
            exit 1
          fi
