name: Secret Audit
on: workflow_dispatch
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Verify 3 GCP secrets
      shell: bash
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        GCP_SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
      run: |
        set -euo pipefail
        red()  { echo "::error::$*"; }
        ok()   { printf "✅ %s\n" "$*"; }
        # 1. Project ID
        [[ "$GCP_PROJECT_ID" == "github-chatgpt-ggcloud" ]] && ok "GCP_PROJECT_ID match" || { red "GCP_PROJECT_ID mismatch"; exit 1; }
        # 2. Service Account
        [[ "$GCP_SERVICE_ACCOUNT" == "chatgpt-deployer@github-chatgpt-ggcloud.iam.gserviceaccount.com" ]] \
          && ok "GCP_SERVICE_ACCOUNT match" || { red "SA mismatch"; exit 1; }
        # 3. Decode JSON key
        EMAIL=$(echo "$GCP_SA_KEY_JSON" | base64 -d 2>/dev/null | jq -r '.client_email')
        [[ "$EMAIL" == "$GCP_SERVICE_ACCOUNT" ]] && ok "GCP_SA_KEY_JSON email match" || { red "JSON key invalid"; exit 1; }
        echo "🎉 Secret format audit PASSED" | tee -a "$GITHUB_STEP_SUMMARY"
