name: Secrets Audit
true:
  workflow_call: null
  schedule:
  - cron: 0 19 * * *
  workflow_dispatch: null
env:
  TZ: Asia/Singapore
jobs:
  secrets-validation:
    name: Validate Secret Expiration
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: pip
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install -r requirements.txt

        '
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        token_format: access_token
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: latest
    - name: Validate secrets expiration
      id: validate
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: 'echo "Running secrets validation (CP6.1 compliance)"

        python scripts/validate_secrets.py

        echo "validation_status=$?" >> $GITHUB_OUTPUT

        '
      continue-on-error: true
    - name: Handle validation results
      run: "validation_status=\"${{ steps.validate.outputs.validation_status }}\"\n\
        echo \"Validation exit code: $validation_status\"\n\ncase $validation_status\
        \ in\n  0)\n    echo \"✅ All secrets validation passed\"\n    ;;\n  1)\n \
        \   echo \"\U0001F6A8 Critical secrets validation failed\"\n    echo \"::error::Critical\
        \ secrets have expired - immediate action required\"\n    exit 1\n    ;;\n\
        \  2)\n    echo \"⚠️ Secrets validation completed with warnings\"\n    echo\
        \ \"::warning::Some secrets are approaching expiration (<15 days)\"\n    #\
        \ Exit 0 for warnings to keep CI green but visible\n    ;;\n  *)\n    echo\
        \ \"❌ Unknown validation status: $validation_status\"\n    echo \"::error::Unexpected\
        \ validation result\"\n    exit 1\n    ;;\nesac\n"
    - name: Report audit completion
      if: always()
      run: 'echo "=== Secrets Audit Summary ==="

        echo "Timestamp: $(date -Iseconds)"

        echo "Timezone: $TZ"

        echo "Status: ${{ job.status }}"

        echo "Validation exit code: ${{ steps.validate.outputs.validation_status }}"

        echo ""

        echo "This audit ensures compliance with:"

        echo "- CP6.1 (Checkpoint Plan V7): Secrets expiration monitoring"

        echo "- HP-05 (Constitution v1.11e): Central Secrets Inheritance"

        echo "- GC-LAW §3: Secret Management"

        echo "- GH-LAW §5.5: Fallback mechanism for sync-secrets downtime"

        '
'on':
  workflow_call: null
