name: Secret Validation Test

on:
  workflow_dispatch:
    inputs:
      check_firebase_secrets:
        description: 'Check if Firebase secrets have values'
        required: false
        default: 'true'
        type: boolean

permissions:
  contents: read

jobs:
  validate-secrets:
    name: Validate Firebase Secrets
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Firebase Secrets
        run: |
          set -euo pipefail

          echo "🔐 Validating Firebase Secrets..."
          echo

          # Check each Firebase secret by testing if it has a value
          # Empty secrets will result in empty strings

          check_secret() {
            local secret_name="$1"
            local secret_value="${!secret_name:-}"

            if [ -z "$secret_value" ]; then
              echo "❌ $secret_name: EMPTY (no value)"
              return 1
            else
              local length=${#secret_value}
              echo "✅ $secret_name: HAS VALUE (length: $length)"
              return 0
            fi
          }

          # Export secrets as environment variables for testing
          export VITE_FIREBASE_API_KEY="${{ secrets.VITE_FIREBASE_API_KEY }}"
          export VITE_FIREBASE_AUTH_DOMAIN="${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}"
          export VITE_FIREBASE_PROJECT_ID="${{ secrets.VITE_FIREBASE_PROJECT_ID }}"
          export VITE_FIREBASE_STORAGE_BUCKET="${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}"
          export VITE_FIREBASE_MESSAGING_SENDER_ID="${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}"
          export VITE_FIREBASE_APP_ID="${{ secrets.VITE_FIREBASE_APP_ID }}"

          echo "Firebase Secrets Validation Results:"
          echo "===================================="

          failed_count=0

          check_secret "VITE_FIREBASE_API_KEY" || ((failed_count++))
          check_secret "VITE_FIREBASE_AUTH_DOMAIN" || ((failed_count++))
          check_secret "VITE_FIREBASE_PROJECT_ID" || ((failed_count++))
          check_secret "VITE_FIREBASE_STORAGE_BUCKET" || ((failed_count++))
          check_secret "VITE_FIREBASE_MESSAGING_SENDER_ID" || ((failed_count++))
          check_secret "VITE_FIREBASE_APP_ID" || ((failed_count++))

          echo
          echo "===================================="
          echo "Summary: $failed_count secrets are empty"

          if [ "$failed_count" -gt 0 ]; then
            echo "❌ Some Firebase secrets are missing values"
            exit 1
          else
            echo "✅ All Firebase secrets have values"
          fi