name: Sync Minimal Secrets

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  sync-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: chatgpt-deployer@github-chatgpt-ggcloud.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyNaCl

      - name: Retrieve PAT from GSM
        run: |
          gcloud secrets versions access latest --secret="gh_pat_sync_secrets" > pat.txt

      - name: Sync secrets to target repository
        run: |
          python .github/scripts/sync_secrets_min.py \
            --repo Huyen1974/agent-data-test \
            --manifest .github/secrets/manifest_min.json \
            --pat-file pat.txt

      - name: Upload sync results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: sync-results
          path: .ci/p169h/sync_result_*.json
