name: Terraform Apply (GATED)
on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type YES to confirm you really want to apply"
        required: true
        default: "NO"

permissions:
  contents: read

env:
  TF_APPLY_ENABLED: "false"     # default deny
  GCS_BACKEND_OK: "false"       # set true only when backend verified

jobs:
  apply:
    # Only run when ALL guards satisfied (manual YES + flags true)
    if: ${{ inputs.confirm == 'YES' && env.TF_APPLY_ENABLED == 'true' && env.GCS_BACKEND_OK == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Guard not satisfied (skip fast-escape)
        if: ${{ !(inputs.confirm == 'YES' && env.TF_APPLY_ENABLED == 'true' && env.GCS_BACKEND_OK == 'true') }}
        run: echo "::notice::Terraform apply gated; skipping by default."; exit 0

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.*"

      - name: Terraform init (GCS backend)
        working-directory: terraform
        run: |
          set -euo pipefail
          terraform init -input=false -no-color

      - name: Terraform apply (explicit gates satisfied)
        working-directory: terraform
        env:
          TF_INPUT: "false"
        run: |
          set -euo pipefail
          terraform apply -auto-approve -input=false -no-color
