name: Test Coverage

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  unit-tests:
    name: Run Unit Tests with Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: app-service-project/package-lock.json

      - name: Install dependencies
        run: npm ci --prefix app-service-project

      - name: Run tests with coverage
        run: npm --prefix app-service-project run test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./app-service-project/coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
